# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
early_access: false

reviews:
  profile: "chill"
  request_changes_workflow: false
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false

  auto_review:
    enabled: true
    drafts: false
    ignore_usernames:
      - "dependabot[bot]"

  path_filters:
    - "!**/node_modules/**"
    - "!**/package-lock.json"
    - "!**/*.png"
    - "!**/*.ipk"
    - "!deploy/webos-app/**"
    - "!deploy/tizen-app/**"

chat:
  auto_reply: true
